# Generated by Django 5.0.3 on 2024-04-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_tecnico', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorariosAtendimentos',
        ),
    ]
