# Generated by Django 5.0.3 on 2024-04-12 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_admin', '0003_vinculotecnicoregional'),
        ('modulo_tecnico', '0002_delete_horariosatendimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosAtendimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now_add=True)),
                ('regional', models.CharField(choices=[('', ''), ('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2)),
                ('dia_semana', models.CharField(max_length=15)),
                ('horario', models.CharField(max_length=10)),
                ('responsavel_atualizacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_atualizacao_horario', to='modulo_admin.usuario')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tecnico_horario_atendimento', to='modulo_admin.usuario')),
            ],
        ),
    ]
