# Generated by Django 5.0.3 on 2024-04-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0003_vinculotecnicoregional'),
        ('modulo_tecnico', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosatendimentos',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico_horario_atendimento', to='modulo_admin.usuario'),
        ),
    ]
