# Generated by Django 5.0.3 on 2024-06-20 13:24

import django.db.models.fields.related
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0021_alter_atendimento_atividade_produtiva_and_more'),
        ('modulo_tecnico', '0004_alter_horariosatendimentos_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('especialidade', models.CharField(choices=[('agricultura_anual', 'Agricultura Anual'), ('apicultura', 'Apicultura'), ('avicultura', 'Avicultura'), ('bovinocultura_leite', 'Bovino de Leite'), ('bovinocultura_corte', 'Bovino de Corte'), ('cafeicultura', 'Cafeicultura'), ('fruticultura', 'Fruticultura'), ('olericultura', 'Olericultura'), ('ovinocaprino_corte', 'Ovinocaprino de Corte'), ('ovinocaprino_leite', 'Ovinocaprino de Leite'), ('piscicultura', 'Piscicultura')], max_length=100)),
                ('status_especialidade', models.BooleanField(default=False)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.related.OneToOneField, related_name='usuario_especialidade', to='modulo_admin.usuario')),
            ],
        ),
    ]
