# Generated by Django 5.0.3 on 2024-04-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0004_vinculoprodutorregional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('atividade_produtiva', models.CharField(choices=[('Bovinocultura de Leite', 'Bovinocultura de Leite')], max_length=120)),
                ('topico', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], max_length=5)),
                ('mais_informacoes', models.TextField(blank=True, null=True)),
                ('imagem01', models.ImageField(null=True, upload_to='')),
                ('imagem02', models.ImageField(null=True, upload_to='')),
                ('imagem03', models.ImageField(null=True, upload_to='')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], max_length=15)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
