# Generated by Django 5.0.3 on 2024-04-18 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0006_atendimento_regional_alter_atendimento_imagem01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico_atendimento', to='modulo_admin.usuario'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='topico',
            field=models.CharField(max_length=120),
        ),
    ]
