# Generated by Django 5.0.3 on 2024-04-20 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0007_atendimento_tecnico_alter_atendimento_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='atendimento_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_posteriores', to='modulo_admin.atendimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='atendimento_retorno',
            field=models.BooleanField(default=False),
        ),
    ]
