# Generated by Django 5.0.3 on 2024-04-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0008_atendimento_atendimento_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='produtor',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtor_atendimento', to='modulo_admin.usuario'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='atividade_produtiva',
            field=models.CharField(choices=[('bovinocultura_leite', 'Bovinocultura de Leite')], max_length=120),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='hora',
            field=models.CharField(max_length=5),
        ),
    ]
