# Generated by Django 5.0.3 on 2024-04-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0009_atendimento_produtor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='produtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtor_atendimento', to='modulo_admin.usuario'),
        ),
    ]
