# Generated by Django 5.0.3 on 2024-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0010_alter_atendimento_produtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='relatorio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='atividade_produtiva',
            field=models.CharField(choices=[('bovinocultura_leite', 'Bovino de Leite')], max_length=120),
        ),
    ]
