# Generated by Django 5.0.3 on 2024-04-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0012_atendimento_relatorio_atualizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido'), ('finalizado', 'Finalizado')], max_length=15),
        ),
        migrations.CreateModel(
            name='AtendimentoConfirmacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('forma_atendimento', models.CharField(choices=[('bovinocultura_leite', 'Bovino de Leite')], max_length=60)),
                ('duracao_minutos', models.PositiveIntegerField()),
                ('qualidade_internet', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento_confirmacao', to='modulo_admin.atendimento')),
            ],
        ),
    ]
