# Generated by Django 5.0.3 on 2024-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0013_alter_atendimento_status_atendimentoconfirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='substatus',
            field=models.CharField(blank=True, choices=[('aguardando_atendimento', 'Aguardando atendimento'), ('cancelado_produtor', 'Cancelado pelo produtor'), ('cancelado_tecnico', 'Cancelado pelo técnico'), ('aguardando_relatorio', 'Aguardando o relatório'), ('aguardando_finalizar', 'Aguardando o técnico finalizar'), ('produtor_avaliar', 'Produtor ainda não avaliou'), ('produtor_nao_abriu_relatorio', 'Produtor não abriu o relatório'), ('produtor_abriu_relatorio', 'Produtor abriu o relatório')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='atendimentoconfirmacao',
            name='forma_atendimento',
            field=models.CharField(choices=[('apenas_audio', 'Apenas áudio'), ('audio_video', 'Áudio e vídeo')], max_length=60),
        ),
    ]
