# Generated by Django 5.0.3 on 2024-04-27 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0014_atendimento_substatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoCancelado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('motivo_cancelamento', models.CharField(choices=[('produtor_nao_compareceu', 'Produtor não compareceu'), ('tecnico_nao_podia_atender', 'Técnico não podia atender'), ('outro_motivo', 'Outro motivo')], max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento_cancelado', to='modulo_admin.atendimento')),
            ],
        ),
    ]
