# Generated by Django 5.0.3 on 2024-04-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0015_atendimentocancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='atendimento_retorno_justificativa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
