# Generated by Django 5.0.3 on 2024-05-01 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0016_atendimento_atendimento_retorno_justificativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='atendimento_retorno',
            new_name='retorno',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='atendimento_anterior',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='atendimento_retorno_justificativa',
        ),
        migrations.CreateModel(
            name='AtendimentoRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('atendimento_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento_anterior', to='modulo_admin.atendimento')),
                ('atendimento_retorno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimento_retorno', to='modulo_admin.atendimento')),
            ],
        ),
    ]
