# Generated by Django 5.0.3 on 2024-05-02 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0017_rename_atendimento_retorno_atendimento_retorno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='avaliacao_atendimento',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
