# Generated by Django 5.0.3 on 2024-05-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0018_atendimento_avaliacao_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicoesFinanceiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('ispb', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=120)),
                ('ord', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='substatus',
            field=models.CharField(blank=True, choices=[('aguardando_atendimento', 'Aguardando atendimento'), ('cancelado_produtor', 'Cancelado pelo produtor'), ('cancelado_tecnico', 'Cancelado pelo técnico'), ('aguardando_relatorio', 'Aguardando o relatório'), ('aguardando_finalizar', 'Aguardando o técnico finalizar'), ('produtor_avaliar', 'Produtor ainda não avaliou'), ('produtor_avaliou', 'Produtor avaliou')], max_length=60, null=True),
        ),
    ]
