# Generated by Django 5.0.3 on 2024-05-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0019_instituicoesfinanceiras_alter_atendimento_substatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_conta', models.CharField(blank=True, choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=100, null=True)),
                ('conta', models.CharField(blank=True, max_length=20, null=True)),
                ('del_status', models.BooleanField(default=False)),
                ('del_data', models.DateTimeField(blank=True, null=True)),
                ('del_cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('banco_codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banco_cnpj', to='modulo_admin.instituicoesfinanceiras')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_cnpj', to='modulo_admin.usuario')),
            ],
        ),
    ]
