# Generated by Django 5.0.3 on 2024-06-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0021_alter_atendimento_atividade_produtiva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocnpj',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
