# Generated by Django 5.0.3 on 2024-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0022_alter_usuariocnpj_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='imagem01',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='imagem02',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='imagem03',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
