# Generated by Django 5.0.3 on 2024-06-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_admin', '0024_atendimento_del_status2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='del_status2',
        ),
    ]
